version: '3.8'

services:
  # Redis cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main application - Development
  chatbot-dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./config:/app/config
      - ollama_models:/root/.ollama
    environment:
      - ENVIRONMENT=development
      - DATABASE_PATH=/app/data/chatbot.db
      - OLLAMA_HOST=http://localhost:11434
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      redis:
        condition: service_healthy
    command: /start_services.sh
    profiles:
      - dev

  # Production application
  chatbot-prod:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
      - ollama_models:/root/.ollama
    environment:
      - ENVIRONMENT=production
      - DATABASE_PATH=/app/data/chatbot.db
      - OLLAMA_HOST=http://localhost:11434
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    profiles:
      - prod

  # Monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitoring

volumes:
  redis_data:
    driver: local
  ollama_models:
    driver: local

networks:
  default:
    name: chatbot-network
